server:
  port: 10099
logging:
  level:
    root: info
    com.dailu.springbootshardingjdbc: debug
###读写分离
#sharding:
#  jdbc:
#    dataSource:
#      # 数据库的名称(多个数据源的名称，与下边同等级的配置项名字相同)
#      names: master,follow1,follow2
#      # 配置主库
#      master: #org.apache.tomcat.jdbc.pool.DataSource
#        type: com.alibaba.druid.pool.DruidDataSource
#        driverClassName: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://127.0.0.1:3306/shardingjdbc?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&useSSL=false&serverTimezone=Asia/Shanghai
#        username: root
#        password: 123456
#        #最大连接数
#        maxPoolSize: 20
#      follow1: # 配置第一个从库
#        type: com.alibaba.druid.pool.DruidDataSource
#        driverClassName: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://127.0.0.1:3306/shardingjdbc?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
#        username: root
#        password: 123456
#        maxPoolSize: 20
#      follow2: # 配置第二个从库
#        type: com.alibaba.druid.pool.DruidDataSource
#        driverClassName: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://127.0.0.1:3306/shardingjdbc?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
#        username: root
#        password: 123456
#        maxPoolSize: 20
#    config:
#      masterslave: # 配置读写分离
#        load-balance-algorithm-type: round_robin # 配置从库选择策略(轮询(round_robin)/随机(random))
#        name: db1s2
#        master-data-source-name: master    #主数据源名称
#        slave-data-source-names: follow1,follow2    #从数据源名称，多个用逗号隔开
#    props:
#      sql: # 开启SQL显示，默认值: false，注意：仅配置读写分离时不会打印日志！！！
#        show: true


sharding:
  jdbc:
    props:
      sql:
        show: true
    config:
      sharding:
        default-database-strategy:
          standard:
#            algorithm-expression: ds_$->{0}
#            algorithm-expression: ds_0
            sharding-column: id
            precise-algorithm-class-name: com.dailu.springbootshardingjdbc.readwrite.algorithm.table.ConsistentShardingAlgorithm
        master-slave-rules:
          ds_0:
            master-data-source-name: ds-master-0
            slave-data-source-names: ds-master-0-slave-0, ds-master-0-slave-1
          ds_1:
            master-data-source-name: ds-master-1
            slave-data-source-names: ds-master-1-slave-0,ds-master-1-slave-1
        tables:
          tb_pay:
            actual-data-nodes: ds_$->{0..1}.tb_pay$->{0..4}
#            actual-data-nodes: ds_0.tb_pay$->{0..4}
#            key-generator-column-name: id
            table-strategy:
              standard:
                precise-algorithm-class-name: com.dailu.springbootshardingjdbc.readwrite.algorithm.table.ConsistentShardingAlgorithm
                sharding-column: id
#        binding-tables:
    datasource:
      ds-master-0:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://127.0.0.1:3306/db_payment0?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
      ds-master-0-slave-0:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://127.0.0.1:3306/db_payment0?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
      ds-master-0-slave-1:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://127.0.0.1:3306/db_payment0?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
      ds-master-1:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://127.0.0.1:3307/db_payment1?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
      ds-master-1-slave-0:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://127.0.0.1:3307/db_payment1?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
      ds-master-1-slave-1:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://127.0.0.1:3307/db_payment1?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT
        username: root
      names: ds-master-0,ds-master-0-slave-0,ds-master-0-slave-1,ds-master-1,ds-master-1-slave-0,ds-master-1-slave-1
mybatis:
  configuration:
    map-underscore-to-camel-case: true
